Mimic.copy(PolyglotWatcherV2.ShellCommandRunner)
Mimic.copy(PolyglotWatcherV2.EnvironmentVariables.SystemWrapper)
Mimic.copy(PolyglotWatcherV2.FileSystem.FileWrapper)
Mimic.copy(PolyglotWatcherV2.Puts)
Mimic.copy(PolyglotWatcherV2.SystemCall)
ExUnit.start()
