#!/bin/bash


MIX_ENV=dev mix escript.build
./polyglot_watcher_v2_dev $@

#!/bin/bash

# ./build

# build_exit_code=$?

# if [[ $build_exit_code -eq 0 ]]; then
#   ./polyglot_watcher_v2 $@
# else
#   echo "The build failed, so I'm not running it mate :-("
# fi
