#!/bin/bash

check_brew_is_installed() {
  command -v brew >/dev/null
  brew_exists_result=$?
  if [[ $brew_exists_result -eq 0 ]]; then
    echo "brew is already installed"
  else
    echo "I require homebrew to be installed first. Do that, then try again"
    exit 1
  fi
}

install_fswatch() {
  command -v fswatch >/dev/null
  fswatch_exists_result=$?
  if [[ $fswatch_exists_result -eq 0 ]]; then
    echo "fswatch is already installed"
  else
    echo "About to install fswatch..."
    brew install fswatch
    install_fswach_result=$?

    if [[ $install_fswach_result -eq 0 ]]; then
      echo "Installed fswatch OK"
    else
      echo "Failed to install fswatch :-( fail. You're on your own now :-("
      exit 1
    fi
  fi
}

check_os_is_debian() {
  (cat /proc/version | grep "Debian") >/dev/null
  debian_result=$?
  if [[ $debian_result -eq 0 ]]; then
    echo "OS is Debian OK"
  else
    echo "I only know how to install for Debian, and you're not debian :-("
    exit 1
  fi
}

install_inotify_tools() {
  (dpkg -l | grep inotify-tools) >/dev/null
  inotify_tools_installed_result=$?
  if [[ $inotify_tools_installed_result -eq 0 ]]; then
    echo "inotify-tools is already installed OK"
  else
    echo "About to install inotify-tools..."
    sudo apt install inotify-tools
    install_inotify_tools_result=$?

    if [[ $install_inotify_tools_result -eq 0 ]]; then
      echo "Installed inotify-tools OK"
    else
      echo "Failed to install inotify-tools :-( fail. You're on your own now :-("
      exit 1
    fi
  fi
}

check_elixir_installed() {
  command -v elixir &> /dev/null
  if [[ $? -eq 0 ]]; then
    echo "elixir is already installed OK"
  else
    echo "I require Elixir to be installed to work. Install Elixir and try again :-("
    exit 1
  fi
}

build() {
  echo "building polyglot_watcher_v2..."
  ./build
  if [[ $? -eq 0 ]]; then
    echo "built polyglot_watcher_v2 OK"
  else
    echo "failed to build polyglot_watcher_v2 :-("
    exit 1
  fi
}

create_symlink() {
  ln -sf $DIR/polyglot_watcher_v2 ~/.local/bin/polyglot_watcher_v2
  if [[ $? -eq 0 ]]; then
    echo "created polyglot_watcher_v2 symlink to ~/.local/bin OK"
  else
    echo "created to create polyglot_watcher_v2 symlink :-("
    exit 1
  fi
}

install_for_mac() {
  check_brew_is_installed
  install_fswatch
  check_elixir_installed
  echo "Everything installed OK"
}

install_for_debian() {
  check_os_is_debian
  install_inotify_tools
  check_elixir_installed
  build
  create_symlink
  echo "Everything installed OK"
  echo "You should now simply be able to run 'polyglot_watcher_v2' now!"
}

case $OSTYPE in
  'darwin20')
    install_for_mac
    ;;
  'linux-gnu')
    install_for_debian
    ;;
  *)
    echo "Installing on your OS $OSTYPE is not yet supported :-("
    exit 1
    ;;
esac
