#!/bin/bash

set -e

section=$(./polyglot_watcher_v2 help_and_quit)
parsed_section="$(echo "$section" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | sed 's/^\(\s*\)/\1 * \1/g' | sed "s/^\s*\*\s*$//g" )"
static_readme=$(cat STATIC_README.md)
echo -e "$static_readme\n\n## Watcher usage and modes\n\nThis section of the readme is the output of running 'help' on the application itself\n$parsed_section" > README.md
